"""Framework content: CyFun 2025 BASIC requirements, guidance summaries and the CCB risk model.

All framework data is loaded from JSON files in this package. basic_2025.json and
risk_model.json are generated by the scripts in scripts/ from the official CCB
workbooks; guidance_basic_2025.json holds short implementation and evidence notes.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

HERE = Path(__file__).parent / "framework"


@dataclass(frozen=True)
class Requirement:
    id: str
    workbook_id: str
    text: str
    key_measure: bool
    sheet: str
    row: int
    function_id: str
    function_name: str
    category_id: str
    category_name: str
    subcategory_id: str
    subcategory_title: str
    guidance: list[str] = field(default_factory=list)
    evidence_examples: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class Subcategory:
    id: str
    title: str
    requirements: tuple[Requirement, ...]


@dataclass(frozen=True)
class Category:
    id: str
    name: str
    description: str
    function_id: str
    function_name: str
    subcategories: tuple[Subcategory, ...]

    @property
    def requirements(self) -> list[Requirement]:
        return [r for s in self.subcategories for r in s.requirements]


@dataclass(frozen=True)
class Function:
    id: str
    name: str
    categories: tuple[Category, ...]

    @property
    def requirements(self) -> list[Requirement]:
        return [r for c in self.categories for r in c.requirements]


class Framework:
    def __init__(self, data: dict, guidance: dict):
        self.meta = {k: v for k, v in data.items() if k != "functions"}
        self.thresholds = data["thresholds"]
        self.maturity_levels = data["maturity_levels"]
        funcs: list[Function] = []
        for f in data["functions"]:
            cats: list[Category] = []
            for c in f["categories"]:
                subs: list[Subcategory] = []
                for s in c["subcategories"]:
                    reqs = []
                    for q in s["requirements"]:
                        g = guidance.get(q["id"], {})
                        reqs.append(
                            Requirement(
                                id=q["id"],
                                workbook_id=q["workbook_id"],
                                text=q["text"],
                                key_measure=q["key_measure"],
                                sheet=q["sheet"],
                                row=q["row"],
                                function_id=f["id"],
                                function_name=f["name"],
                                category_id=c["id"],
                                category_name=c["name"],
                                subcategory_id=s["id"],
                                subcategory_title=s["title"],
                                guidance=list(g.get("guidance", [])),
                                evidence_examples=list(g.get("evidence", [])),
                            )
                        )
                    subs.append(Subcategory(s["id"], s["title"], tuple(reqs)))
                cats.append(Category(c["id"], c["name"], c["description"], f["id"], f["name"], tuple(subs)))
            funcs.append(Function(f["id"], f["name"], tuple(cats)))
        self.functions: tuple[Function, ...] = tuple(funcs)
        self.categories: list[Category] = [c for f in funcs for c in f.categories]
        self.requirements: list[Requirement] = [r for f in funcs for r in f.requirements]
        self.by_id: dict[str, Requirement] = {r.id: r for r in self.requirements}
        self.key_measures: list[Requirement] = [r for r in self.requirements if r.key_measure]

    def get(self, requirement_id: str) -> Requirement | None:
        return self.by_id.get(requirement_id)

    def neighbours(self, requirement_id: str) -> tuple[Requirement | None, Requirement | None]:
        ids = [r.id for r in self.requirements]
        i = ids.index(requirement_id)
        prev_ = self.requirements[i - 1] if i > 0 else None
        next_ = self.requirements[i + 1] if i < len(ids) - 1 else None
        return prev_, next_


@lru_cache
def load_framework() -> Framework:
    data = json.loads((HERE / "basic_2025.json").read_text(encoding="utf-8"))
    guidance = json.loads((HERE / "guidance_basic_2025.json").read_text(encoding="utf-8"))
    return Framework(data, guidance)


@lru_cache
def load_risk_model() -> dict:
    return json.loads((HERE / "risk_model.json").read_text(encoding="utf-8"))
