"""Framework content: CyFun 2025 requirements per assurance level, guidance and the CCB risk model.

All framework data is loaded from JSON files in this package:

* basic_2025.json, important_2025.json, essential_2025.json: generated by scripts/build_framework.py
  from the official CCB self-assessment workbooks (requirements, levels, key measures, thresholds,
  N/A rules, cell layout for the export, and the aggregation groups behind each category score,
  parsed from the workbook's own formulas).
* goals_2025.json: the goal statement of each requirement, extracted from the CCB booklets by
  scripts/build_goals.py.
* guidance_basic_2025.json: short implementation and evidence notes written for this project.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

HERE = Path(__file__).parent / "framework"
LEVELS = ("BASIC", "IMPORTANT", "ESSENTIAL")
LEVEL_RANK = {"Basic": 0, "Important": 1, "Essential": 2}


def normalise_level(value: str | None) -> str:
    v = (value or "BASIC").strip().upper()
    return v if v in LEVELS else "BASIC"


@dataclass(frozen=True)
class Requirement:
    id: str
    workbook_id: str
    text: str
    level: str  # Basic | Important | Essential (the level that introduces the requirement)
    key_measure: bool
    management_aspect: bool
    management_label: str
    sheet: str
    row: int
    function_id: str
    function_name: str
    category_id: str
    category_name: str
    subcategory_id: str
    subcategory_title: str
    goal: str = ""
    guidance: list[str] = field(default_factory=list)
    evidence_examples: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class Subcategory:
    id: str
    title: str
    requirements: tuple[Requirement, ...]


@dataclass(frozen=True)
class Category:
    id: str
    name: str
    description: str
    function_id: str
    function_name: str
    subcategories: tuple[Subcategory, ...]
    # Aggregation groups behind the workbook's category score, per dimension: tuples of requirement ids.
    # Normally one group per subcategory; the CCB workbooks deviate in a few places and the groups follow them.
    score_groups_doc: tuple[tuple[str, ...], ...] = ()
    score_groups_impl: tuple[tuple[str, ...], ...] = ()

    @property
    def requirements(self) -> list[Requirement]:
        return [r for s in self.subcategories for r in s.requirements]

    def groups(self, dimension: str) -> tuple[tuple[str, ...], ...]:
        g = self.score_groups_doc if dimension == "doc" else self.score_groups_impl
        return g or tuple(tuple(r.id for r in s.requirements) for s in self.subcategories)


@dataclass(frozen=True)
class Function:
    id: str
    name: str
    categories: tuple[Category, ...]

    @property
    def requirements(self) -> list[Requirement]:
        return [r for c in self.categories for r in c.requirements]


class Framework:
    def __init__(self, data: dict, guidance: dict, goals: dict):
        self.level: str = data["level"]
        self.meta = {k: v for k, v in data.items() if k != "functions"}
        self.thresholds: dict = data["thresholds"]
        self.layout: dict = data["layout"]
        self.maturity_levels = data["maturity_levels"]
        self.quirks: list[str] = list(data.get("quirks", []))
        funcs: list[Function] = []
        for f in data["functions"]:
            cats: list[Category] = []
            for c in f["categories"]:
                subs: list[Subcategory] = []
                for s in c["subcategories"]:
                    reqs = []
                    for q in s["requirements"]:
                        g = guidance.get(q["id"], {})
                        reqs.append(
                            Requirement(
                                id=q["id"],
                                workbook_id=q["workbook_id"],
                                text=q["text"],
                                level=q["level"],
                                key_measure=q["key_measure"],
                                management_aspect=q.get("management_aspect", False),
                                management_label=q.get("management_label", ""),
                                sheet=q["sheet"],
                                row=q["row"],
                                function_id=f["id"],
                                function_name=f["name"],
                                category_id=c["id"],
                                category_name=c["name"],
                                subcategory_id=s["id"],
                                subcategory_title=s["title"],
                                goal=(goals.get(q["id"]) or {}).get("goal", ""),
                                guidance=list(g.get("guidance", [])),
                                evidence_examples=list(g.get("evidence", [])),
                            )
                        )
                    subs.append(Subcategory(s["id"], s["title"], tuple(reqs)))
                sg = c.get("score_groups") or {}
                cats.append(
                    Category(
                        c["id"],
                        c["name"],
                        c["description"],
                        f["id"],
                        f["name"],
                        tuple(subs),
                        tuple(tuple(g) for g in sg.get("doc", [])),
                        tuple(tuple(g) for g in sg.get("impl", [])),
                    )
                )
            funcs.append(Function(f["id"], f["name"], tuple(cats)))
        self.functions: tuple[Function, ...] = tuple(funcs)
        self.categories: list[Category] = [c for f in funcs for c in f.categories]
        self.requirements: list[Requirement] = [r for f in funcs for r in f.requirements]
        self.by_id: dict[str, Requirement] = {r.id: r for r in self.requirements}
        self.key_measures: list[Requirement] = [r for r in self.requirements if r.key_measure]
        self.management_aspects: list[Requirement] = [r for r in self.requirements if r.management_aspect]

    @property
    def tool_version(self) -> str:
        return self.meta.get("source", {}).get("tool_version", "")

    def get(self, requirement_id: str) -> Requirement | None:
        return self.by_id.get(requirement_id)

    def neighbours(self, requirement_id: str) -> tuple[Requirement | None, Requirement | None]:
        ids = [r.id for r in self.requirements]
        i = ids.index(requirement_id)
        prev_ = self.requirements[i - 1] if i > 0 else None
        next_ = self.requirements[i + 1] if i < len(ids) - 1 else None
        return prev_, next_

    def count_by_level(self) -> dict[str, int]:
        out: dict[str, int] = {}
        for r in self.requirements:
            out[r.level] = out.get(r.level, 0) + 1
        return out


def _read(name: str) -> dict:
    p = HERE / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


@lru_cache
def load_framework(level: str = "BASIC") -> Framework:
    level = normalise_level(level)
    data = json.loads((HERE / f"{level.lower()}_2025.json").read_text(encoding="utf-8"))
    return Framework(data, _read("guidance_basic_2025.json"), _read("goals_2025.json"))


@lru_cache
def load_risk_model() -> dict:
    return json.loads((HERE / "risk_model.json").read_text(encoding="utf-8"))


@lru_cache
def all_requirement_ids() -> dict[str, str]:
    """Every requirement id across levels with the level that introduces it (ESSENTIAL is the superset)."""
    fw = load_framework("ESSENTIAL")
    return {r.id: r.level for r in fw.requirements}
